language: cpp
sudo: required
python:          3.6
dist:            trusty

matrix:
  include:
    - os: linux
      sudo: required
      compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports]
          packages:
            - g++-7
            - zlib1g-dev
            - libbz2-dev
            - libboost-dev
            - cmake
            - cmake-data
            - make
            - automake
            - python
            - python-nose
            - python-jinja2
            - python-pip

      env:
        - MB_PYTHON_VERSION=3.6

before_install:
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 70 --slave /usr/bin/g++ g++ /usr/bin/g++-7
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda3.sh;
  - chmod +x miniconda3.sh
  - ./miniconda3.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda

install:
  - export PATH=/home/travis/miniconda3/bin:$PATH
  - conda create --yes -n env_kprocessor python=$MB_PYTHON_VERSION
  - source activate env_kprocessor
  - conda install --yes -c conda-forge swig=4.0.1
  - conda install --yes pytest
  - BACK=$(pwd)
  - pwd
  - echo "Python version $(which python)"
  - echo "******** Building kProcessor ********"
  - mkdir build && cd build
  - cmake ..
  - make
  - cd ${BACK}
  - echo "******** Running kProcessor CPP Test Cases ********"
  - cd ./build/tests/kProcessorLibTests
  # - ./testKprocessorLib


script:
  - cd ${BACK}
  - echo "******** Building Python Interface ********"
  - $(which python) setup.py bdist_wheel
  - cd dist/
  - $(which python) -m pip install kProcessor*whl
  - cd ${BACK}
  - echo "******** Running Python Interface Test Cases ********"
  - echo "Python version $(which python)"
  - cd ${BACK}
  # - cd ./tests/python/
  # - pytest

branches:
  only:
  - master
  - development
  - beta_v1

after_success:
  - bash <(curl -s https://codecov.io/bash)
