pepfile: "project_config.yaml"
configfile: "config.yaml"

kSize=config["kSize"]
transpictome=list(filter(lambda x:x.library=="transpictome",pep.samples))[0].file[0]


def getFastq(name):
    return list(filter(lambda x:x.sample_name==name,pep.samples))[0].file


kFrameType="mqf"
kFrameTypeC="MQF"

samplesKDataframe=list(filter(lambda x:x.library=="sample",pep.samples))
samplesKDataframe=["kDataframe."+x.sample_name+"."+kFrameType for x in samplesKDataframe]
controlKDataframe=list(filter(lambda x:x.library=="control",pep.samples))
controlKDataframe=["kDataframe."+x.sample_name+"."+kFrameType for x in controlKDataframe]


rule all:
    input: "kDifferntialExpression.median_ttest.lst"

rule kDifferntialExpression:
    input:
         sample=samplesKDataframe,
         control=controlKDataframe,
         transpictome=transpictome
    output: "kDifferntialExpression.median_ttest.lst"
    log: "kDifferntialExpression.log"
    shell:
       	"""
        echo {input.sample} | sed -e 's/.{kFrameType}//g'|tr -s ' ' $'\n' > sample
        echo {input.control} | sed -e 's/.{kFrameType}//g'|tr -s ' ' $'\n' > control   	
	./kDifferntialExpression -g {input.transpictome} -s sample -c control -o {output} 
        """

rule kmc:
    input: lambda wildcards: getFastq(f"{wildcards.experiment}"),         
    output:
         kDataframe="kDataframe.{experiment}."+kFrameType,
         time="{experiment}.kmc.time"
    conda:
         "env.yaml"
    threads: 4
    log: "{experiment}.kmc.log"
    shell:
       	"""
	echo {input} |tr -s ' ' $'\n' > {wildcards.experiment}.lst
	/usr/bin/time -v -o {output.time} kmc -ci1 -t{threads} -k{kSize} -m2  @{wildcards.experiment}.lst {wildcards.experiment}  ./ &> {log}
	../../apps/loadFromKMC {wildcards.experiment} {kFrameTypeC} kDataframe.{wildcards.experiment} 
        """

