name: Ubuntu

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install boost
        run: sudo apt-get install libboost-all-dev

      # - name: configure
      #   run: cmake -Stest -Bbuild -DENABLE_TEST_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug

      - name: configure
        run: cmake -Bbuild -DBUILD_ALL=1

      - name: build
        run: cmake --build build -j4

      # - name: test
      #   run: |
      #     cd build
      #     ctest --build-config Debug
      - name: collect code coverage
        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
