name: Ubuntu

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: install boost
        run: sudo apt-get install libboost-all-dev
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
        
      - name: install_cmake
        run: pip install cmake

      # - name: configure
      #   run: cmake -Stest -Bbuild -DENABLE_TEST_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug

      - name: configure
        run: cmake -Bbuild

      - name: build
        run: cmake --build build -j4

      # - name: test
      #   run: |
      #     cd build
      #     ctest --build-config Debug
      - name: collect code coverage
        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"