name: Ubuntu

on: [push, pull_request]

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
    
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:   
         cmake-version: 'latest'
      - name: Use cmake
        run: cmake --version
      - name: Use g++
        run: g++ --version  
      - name: install dependecies
        run: sudo apt-get install  swig cmake python3-dev zlib1g-dev libghc-bzlib-dev python3-distutils libboost-all-dev

      # - name: configure
      #   run: cmake -Stest -Bbuild -DENABLE_TEST_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug

      - name: configure
        run: cmake -Bbuild -DBUILD_ALL=1

      - name: build
        run: cmake --build build -j1

      # - name: test
      #   run: |
      #     cd build
      #     ctest --build-config Debug
      - name: collect code coverage
        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
